[package]
name = "rustlv"
version = "0.1.0"
authors = ["hushui502 <502131010@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"