[package]
name = "rustlings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug-backfill = []

[dependencies]
peg = "0.6.2"
argh = "0.1.3"
color-backtrace = "0.3.0"
ctor = "0.1.14"