---
kind: pipeline
name: default

steps:
  - name: build & run tests
    image: r.mills.io/prologic/golang-alpine
    commands:
      - make build
      - make test

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - tag
    - push
    - pull_request
